[package]
name = "tsvkit"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
clap = { version = "4.4", features = ["derive"] }
csv = "1.3"
indexmap = "2.2"
itertools = "0.12"
regex = "1"
